### ISSUE TITLE
I get {   "message": "Forbidden" }

### ISSUE THREAD

**Issue by kjetilge** [maxdarque/up-graphql-yoga-server-example#2]
I followed the tutorial and get  ```{   "message": "Forbidden"  }``` when playground opens at "my-aws-api-url.com/staging/".

I also tried to change the url to  "my-aws-api-url.com/development/" but  then I only get a white page with the same message. I used the IAM Policy recommended in  the Apex Up manual - but I guess since everything deploys fine - it's irrelevant.

This is the deployment: https://r9tiudkyrf.execute-api.eu-west-1.amazonaws.com/staging/

I checked that my endpoint actually works by querying it (using token in playground).
Here it is: https://eu1.prisma.sh/geirbo/up-graphql-yoga-server-example/dev

**Comment by maxdarque** [comment]
Sorry just saw this. So when you open the playground which url does it show you to the right of HISTORY?  When I clicked on your link it gave me https://r9tiudkyrf.execute-api.eu-west-1.amazonaws.com/ and you need to add `staging`. 

Which version of `Apex/up` are you using? There was a breaking change in the tutorial following the release of Up 0.5+. Please make sure you have the right IAM policy in place. Either see the tutorial or the Up docs https://up.docs.apex.sh/

New IAM policy

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "acm:*",
                "cloudformation:Create*",
                "cloudformation:Delete*",
                "cloudformation:Describe*",
                "cloudformation:ExecuteChangeSet",
                "cloudformation:Update*",
                "cloudfront:*",
                "cloudwatch:*",
                "ec2:*",
                "ecs:*",
                "events:*",
                "iam:AttachRolePolicy",
                "iam:CreatePolicy",
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:DeleteRolePolicy",
                "iam:GetRole",
                "iam:PassRole",
                "iam:PutRolePolicy",
                "lambda:AddPermission",
                "lambda:Create*",
                "lambda:Delete*",
                "lambda:Get*",
                "lambda:InvokeFunction",
                "lambda:List*",
                "lambda:RemovePermission",
                "lambda:Update*",
                "logs:Create*",
                "logs:Describe*",
                "logs:FilterLogEvents",
                "logs:Put*",
                "logs:Test*",
                "route53:*",
                "route53domains:*",
                "s3:*",
                "ssm:*",
                "sns:*"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "apigateway:*",
            "Resource": "arn:aws:apigateway:*::/*"
        }
    ]
}
```

**Comment by maxdarque** [comment]
I added `staging` to your url inside the playground (i.e. not your browser url bar).

I queried 
```
{
  me {
    id
  }
}
```

```json
{
  "data": {
    "me": null
  },
  "errors": [
    {
      "message": "Not authorized",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "me"
      ]
    }
  ]
}
```

So it looks like it's working

**Comment by abelovic** [comment]
I'm getting the "not authorized" as well. Do I need to pass a token in the header?

**Comment by maxdarque** [comment]
@abelovic The "Not authorized" response is expected behavior if you're not logged in.

I suggest you look at your code and see how you've implemented authentication. The advanced boilerplates here are a good start: https://github.com/graphql-boilerplates

you'll need to authenticate the user with something like:

```
mutation {
  authenticateUser(
    email: "name@your-domain.com"
    password: "password"
  ) {
    user {
      id
      name
      email
    }
    token
  }
}
```

Then copy and paste the token into the playground under `HTTP HEADERS` in the following format:

```
{"Authorization": "Bearer <your-token>"}
```

**Comment by abelovic** [comment]
@maxdarque - Thank you - that worked! I was thinking that it was AWS Gateway denying me and couldn't figure out what I was doing wrong in the settings ;)
