### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by abelovic** [maxdarque/up-graphql-yoga-server-example#3]
I can connect fine from the playground but getting CORS errors when calling from apollo client in a web page. I have:

- Enabled CORS in AWS Gateway (and deployed) 
- my up.json is as follows (and my app is running on localhost port 3000):

  "cors": {
    "allowed_origins": ["http://localhost:3000"],
    "allowed_methods": ["HEAD", "GET", "POST"],
    "allowed_headers": ["*"]
  }
- followed the boilerplate for setting up apollo client: https://github.com/graphql-boilerplates/vue-fullstack-graphql/blob/master/advanced/src/main.js

This is what I get:

Failed to load https://10t6y41fnc.execute-api.us-east-1.amazonaws.com/development: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 500. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

What am I missing?

**Comment by maxdarque** [comment]
@abelovic 
Why did you enable CORS in API Gateway? I think Apex Up does the configuration for you.

My understanding is that the CORS configuration in `up.json` is applied upon each deploy (i.e. you can't use `up stack apply`). When you change the CORS config, do you re-deploy?

In your browser in console under Network (in Chrome), what does **origin** say under **Request Headers**?

**Comment by abelovic** [comment]
I first tried it "as is" and got the CORS error. Then I tried to enable CORS in Gateway to see if it would resolve it but it did not. I have done it from scratch as well as a redeploy.

I would also think up would have set the CORS headers. Couldn't find any additional info about this.

Have you tried this from a web page (it works perfect from the playground)? You didn't get any errors?

Here are the headers in Chrome:

General:

Request URL:https://10t6y41fnc.execute-api.us-east-1.amazonaws.com/development
Request Method:OPTIONS
Status Code:500 
Remote Address:13.32.170.173:443
Referrer Policy:no-referrer-when-downgrade

Response:

content-length:36
content-type:application/json
date:Thu, 15 Mar 2018 20:19:38 GMT
status:500
via:1.1 b25849ddbbda4851653d50ca55827971.cloudfront.net (CloudFront)
x-amz-cf-id:YcEaGBKWyoC-UH8at2X31aR59q7bAVBWZPgaV-c_yvZEOJr2WF9lIw==
x-amzn-requestid:2f7e3f9c-288e-11e8-b6cb-a96bf2995ffe
x-cache:Error from cloudfront

Request:

:authority:10t6y41fnc.execute-api.us-east-1.amazonaws.com
:method:OPTIONS
:path:/development
:scheme:https
accept:*/*
accept-encoding:gzip, deflate, br
accept-language:en-US,en;q=0.9
access-control-request-headers:authorization,content-type
access-control-request-method:POST
origin:http://localhost:3000
referer:http://localhost:3000/queue/history
user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by maxdarque** [comment]
What version of `up` are you using?

When I try your URL, I get the following error:

```
{
   message: "Internal server error"
}
```

I see the following in the console:

```
Failed to load resource: the server responded with a status of 403 ()
development Failed to load resource: the server responded with a status of 502 ()
```

Here's the response header from the api call:

```

content-length:36
content-type:application/json
date:Thu, 15 Mar 2018 20:27:46 GMT
status:502
via:1.1 40aba1f2d18f4a578f447caa4526a36d.cloudfront.net (CloudFront)
x-amz-cf-id:2eAe-Af2mTAiJhgdWv7KROAHDwzf4ZcW8XwQCgtRD3aTj8iRK0-Uog==
x-amzn-requestid:49a8bef6-288f-11e8-b71a-69365a792915
x-cache:Error from cloudfront
```

**Comment by maxdarque** [comment]
I can access the playground on your production server
https://10t6y41fnc.execute-api.us-east-1.amazonaws.com/production

Can you connect your app to the production api?

**Comment by maxdarque** [comment]
Wait I'm being an idiot. With the 0.5+ version of Up, there is no api/development deployment. You run development locally and deploy to /staging and /production on AWS Lambda. I'll update the reference in the README.md

**Comment by abelovic** [comment]
Yes that worked!

As far as the link not working, it was because I was playing around with options passed into the graphql-yoga server to see if I could set cors in the middleware. I passed it something wrong and didn't redeploy on aws ;) Just removed that and pushed it back up so it should be running with the development stage. This works for playground but not from an app (because of what you said above)

Actually it looks like I am using an old version 0.4.12. I will upgrade this just to make sure I don't have any other weird version issues.

On a side note: I saw you responded to this: https://github.com/jgeschwendt/serverless-prisma

Is this any difference from your solution with up? I originally tried doing what he did with serverless but could never get it to work. Serverless runs better for me on windows 10 because I have to use the built in bash with up and its just not that great ;/

**Comment by maxdarque** [comment]
Okay when you upgrade, make sure you update the IAM policy as it has changed. If you don't it, Up won't be able to deploy to AWS.

I've not used Serverless with this so difficult for me to compare. It certainly looks interesting and another good way of deploying your server. I'm going to stick with Up because I'm on MacOS and it works well enough. It's easy to deploy and I don't think about it much. Up manages your SSL certificates on your chosen domains which I love.

**Comment by maxdarque** [comment]
Glad to hear that it's working :)

**Comment by abelovic** [comment]
Will do on the policy. Thanks so much for your help!
